# Generated by Django 2.0.7 on 2018-08-02 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brief', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField(default=100)),
                ('admins', models.ManyToManyField(blank=True, related_name='group_admins', to='catalog.UserProfile')),
                ('members', models.ManyToManyField(blank=True, related_name='group_members', to='catalog.UserProfile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.UserProfile')),
            ],
            options={
                'verbose_name': 'eventgroups',
                'verbose_name_plural': 'eventgroups',
            },
        ),
    ]
